'use strict';

export default {
    "Armor Layering": 1,
    "EM Armor Compensation": 2,
    "Explosive Armor Compensation": 2,
    "Hull Upgrades": 5,
    "Kinetic Armor Compensation": 2,
    "Mechanics": 5,
    "Remote Armor Repair Systems": 3,
    "Remote Hull Repair Systems": 2,
    "Repair Systems": 5,
    "Thermal Armor Compensation": 2,
    "Corporation Management": 1,
    "Drone Avionics": 4,
    "Drone Durability": 4,
    "Drone Interfacing": 4,
    "Drone Navigation": 4,
    "Drone Sharpshooting": 4,
    "Drones": 5,
    "Light Drone Operation": 5,
    "Medium Drone Operation": 5,
    "Repair Drone Operation": 2,
    "Heavy Drone Operation": 4,
    "Amarr Drone Specialization": 2,
    "Caldari Drone Specialization": 2,
    "Gallente Drone Specialization": 2,
    "Minmatar Drone Specialization": 2,
    "Electronic Warfare": 4,
    "Propulsion Jamming": 4,
    "Weapon Disruption": 4,
    "Sensor Linking": 3,
    "Target Painting": 3,
    "Advanced Weapon Upgrades": 3,
    "CPU Management": 5,
    "Capacitor Emission Systems": 4,
    "Capacitor Management": 4,
    "Capacitor Systems Operation": 3,
    "Electronics Upgrades": 5,
    "Energy Grid Upgrades": 5,
    "Energy Pulse Weapons": 2,
    "Power Grid Management": 5,
    "Thermodynamics": 4,
    "Weapon Upgrades": 5,
    "Controlled Bursts": 4,
    "Gunnery": 5,
    "Medium Energy Turret": 5,
    "Motion Prediction": 4,
    "Rapid Firing": 4,
    "Sharpshooter": 4,
    "Small Energy Turret": 5,
    "Surgical Strike": 4,
    "Trajectory Analysis": 4,
    "Small Pulse Laser Specialization": 3,
    "Medium Pulse Laser Specialization": 3,
    "Small Beam Laser Specialization": 3,
    "Medium Beam Laser Specialization": 3,
    "Large Energy Turret": 4,
    "Small Blaster Specialization": 3,
    "Medium Blaster Specialization": 3,
    "Small Rail Specialization": 3,
    "Medium Rail Specializatoin": 3,
    "Large Hybrid Turret": 4,
    "Small Autocannon Specialization": 3,
    "Medium Autocannon Specialization": 3,
    "Small Artillery Specialization": 3,
    "Medium Artillery Specialization": 3,
    "Large Projectile Turret": 4,
    "Rocket Specialization": 3,
    "Heavy Missile Specialization": 3,
    "Light Missile Specialization": 3,
    "Heavy Assault Missile Specialization": 3,
    "Medium Hybrid Turret": 5,
    "Small Hybrid Turret": 5,
    "Medium Projectile Turret": 5,
    "Small Projectile Turret": 5,
    "Leadership": 3,
    "Torpedoes": 4,
    "Cruise Missiles": 4,
    "Guided Missile Precision": 3,
    "Missile Launcher Operation": 5,
    "Light Missiles": 5,
    "Heavy Assault Missiles": 5,
    "Heavy Missiles": 5,
    "Missile Bombardment": 4,
    "Missile Projection": 2,
    "Rapid Launch": 4,
    "Rockets": 5,
    "Target Navigation Prediction": 3,
    "Warhead Upgrades": 3,
    "Acceleration Control": 3,
    "Afterburner": 3,
    "Evasive Maneuvering": 3,
    "High Speed Maneuvering": 3,
    "Navigation": 4,
    "Warp Drive Operation": 3,
    "Biology": 3,
    "Cybernetics": 3,
    "Infomorph Psychology": 1,
    "Industry": 5,
    "Mass Production": 3,
    "Mining": 4,
    "Ice Harvesting": 2,
    "Mining Upgrades": 4,
    "Reprocessing": 3,
    "Gas Cloud Harvesting": 2,
    "Salvaging": 3,
    "Armor Rigging": 3,
    "Astronautics Rigging": 3,
    "Hybrid Weapon Rigging": 3,
    "Launcher Rigging": 3,
    "Shield Rigging": 3,
    "Projectile Weapon Rigging": 3,
    "Drones Rigging": 3,
    "Electronic Superiority Rigging": 3,
    "Energy Weapon Rigging": 3,
    "Jury Rigging": 3,
    "Archaeology": 3,
    "Astrometric Acquisition": 2,
    "Astrometric Rangefinding": 2,
    "Astrometrics": 3,
    "Hacking": 3,
    "Survey": 3,
    "Science": 4,
    "EM Shield Compensation": 2,
    "Explosive Shield Compensation": 2,
    "Kinetic Shield Compensation": 2,
    "Shield Emission Systems": 3,
    "Shield Compensation": 4,
    "Shield Management": 4,
    "Shield Operation": 4,
    "Shield Upgrades": 4,
    "Tactical Shield Manipulation": 4,
    "Thermal Shield Compensation": 2,
    "Connections": 2,
    "Criminal Connections": 2,
    "Diplomacy": 3,
    "Distribution Connections": 2,
    "Mining Connections": 2,
    "Negotiation": 2,
    "Security Connections": 2,
    "Social": 3,
    "Amarr Battlecruiser": 4,
    "Amarr Battleship": 4,
    "Caldari Battlecruiser": 4,
    "Caldari Battleship": 4,
    "Minmatar Battlecruiser": 4,
    "Minmatar Battleship": 4,
    "Gallente Battlecruiser": 4,
    "Gallente Battleship": 4,
    "Amarr Cruiser": 4,
    "Amarr Destroyer": 4,
    "Amarr Frigate": 4,
    "Amarr Industrial": 1,
    "Mining Frigate": 4,
    "Spaceship Command": 4,
    "Caldari Cruiser": 4,
    "Caldari Destroyer": 4,
    "Caldari Frigate": 4,
    "Caldari Industrial": 1,
    "Gallente Cruiser": 4,
    "Gallente Destroyer": 4,
    "Gallente Frigate": 4,
    "Gallente Industrial": 1,
    "Minmatar Cruiser": 4,
    "Minmatar Destroyer": 4,
    "Minmatar Frigate": 4,
    "Minmatar Industrial": 1,
    "Anchoring": 1,
    "Long Range Targeting": 3,
    "Signature Analysis": 3,
    "Target Management": 4,
    "Broker Relations": 2,
    "Marketing": 2,
    "Trade": 3
};